### ISSUE TITLE
standardize names

### ISSUE THREAD

**Issue by RobertMyles** [RobertMyles/congressbr#12]
Just check to standardize the variable names in the data frames returned. If one df has `party_id`, for example, the same info should be `party_id` in all data frames, unless it's very specific to something else.

**Comment by RobertMyles** [comment]
For example, there are variables in the Senate part that are `bill_number`, whereas in the Chamber they are `number_bill`. Let's standardize them? (I'm going to suggest the Senate way :-D )

**Comment by danilofreire** [comment]
Other things should probably be standardised too:

- if we're using `sen_` for the senate, wouldn't it be better to use `cha_` for the chamber of deputies? 
- people will probably search for bills using the type, so maybe renaming `cam_bill_info_tny.R` to `cam_bill_info.R` would be more intuitive
- if possible, merge the original `cam_bill_info_tny.R` into the new function, with bill id as an argument

@RobertMyles and @duarteguilherme, any ideas?

**Comment by duarteguilherme** [comment]
I'll standardize bill_number later.

**Comment by duarteguilherme** [comment]
What do you think about "cham" instead of "cam"? I think it's a better option

**Comment by danilofreire** [comment]
Yes, I said that on Facebook a few minutes ago. It could either be `cha_` or `cham_`, although the last sounds betters to me. Easier to pronounce in English.

**Comment by RobertMyles** [comment]
`cham_` looks good to me.

**Comment by danilofreire** [comment]
Great, so let's rename the functions. I can do it if you guys want me to, then update the vignettes. Is that okay?

**Comment by duarteguilherme** [comment]
Just have to update the vignettes

**Comment by danilofreire** [comment]
Closed with commit [#1f9fcd1](https://github.com/RobertMyles/congressbr/commit/1f9fcd166bc8a1daf6ac3b9bf5d79ee82097e2c6). I checked every function and updated the vignettes. The package compiles without errors on my machine.
