### ISSUE TITLE
Inclusions for future versions

### ISSUE THREAD

**Issue by RobertMyles** [RobertMyles/congressbr#16]
If they are available, it would be great to include data from city chambers. I see São Paulo has open data, but I don't see an API ([http://www.camara.sp.gov.br/atividade-legislativa/splegis-consulta/](http://www.camara.sp.gov.br/atividade-legislativa/splegis-consulta/)). I don't know if any cities have this info, but it would be great to have it as part of the package.

**Comment by danilofreire** [comment]
Great idea! I really like it. However, do all that would take a lot of work. Maybe we should do it in another version of the package? It would be nice if we could release the package first, with the main functions (national level), then work on it later after the package is out. What do you guys think?

**Comment by RobertMyles** [comment]
Sure, maybe that's a better idea!

**Comment by danilofreire** [comment]
It's just a suggestion, I don't know :) It's just that we can speed the release of the package if we just focus on the federal legislative. Maybe state-level câmaras are the next step? :)

**Comment by RobertMyles** [comment]
I agree, we can work on it later. I'm not even sure if the data exists in a way that we can get at easily. If so, it can be the next version...or if someone wants to do it as a pull request, that would be great.

**Comment by danilofreire** [comment]
Absolutely. Let's leave the issue open, maybe someone is interested in doing that. Or we can do it for version 1.1.0 :)

**Comment by RobertMyles** [comment]
Just leaving a checklist here for inclusions in future versions:

- senator leadership information
