### ISSUE TITLE
improve code documentation

### ISSUE THREAD

**Issue by danilofreire** [RobertMyles/congressbr#2]
Document what is returned from functions (columns and values etc.)

**Comment by RobertMyles** [comment]
I'm also not sure what some of the variables represent in the results from the Senate. In `sen_senator`, for example, there is a leadership list, with variables that, as of yet, have no documentation on the API.

**Comment by danilofreire** [comment]
Should we write the Senate and ask for more info on the API?

**Comment by RobertMyles** [comment]
Maybe! Good idea.

**Comment by danilofreire** [comment]
Just tell me what you want to know, if more than that, and I'll write a
formal email to the Senate. I'm not sure they'll reply because, well, it's
the Brazilian bureaucracy. But we might give it a shot!

**Comment by RobertMyles** [comment]
Great. I'll compile a list of the things I'm not sure of.

**Comment by danilofreire** [comment]
Kewl, maybe it's better if we write a single email. What do you think?

**Comment by RobertMyles** [comment]
Yeah, I think that'd probably be better. Or we could bombard them with 8 million...

**Comment by RobertMyles** [comment]
#3 and #12 can be closed with this, it's all part of the same thing.

**Comment by danilofreire** [comment]
We can close it with [#18](https://github.com/RobertMyles/congressbr/issues/18).
