### ISSUE TITLE
Error in cam_get_votes.R is not properly solved

### ISSUE THREAD

**Issue by duarteguilherme** [RobertMyles/congressbr#20]
There is an error related to a API problem. I used a general tryCatch solution, but it doesn't sound proper to me.

**Comment by RobertMyles** [comment]
What's the error?

**Comment by duarteguilherme** [comment]
It's not an error, just a reminder to improve the code. It returns a warning, I have to check it in order to know what's going on. I'll have a butcher later.

**Comment by duarteguilherme** [comment]
I guess it's solved

**Comment by RobertMyles** [comment]
Ok, china plate.
