### ISSUE TITLE
Data prep for Stan, JAGS, etc.

### ISSUE THREAD

**Issue by RobertMyles** [RobertMyles/congressbr#22]
Some functions that prepare vote data for use with ideal-point analyses would be great. We'll need to import the rollcall function from pscl for wnominate and ideal. JAGS and MCMCpack take a matrix of roll calls, and Stan takes this matrix as a vector with the NA deleted out.

**Comment by danilofreire** [comment]
That's a great idea! It would help tremendously those who work with ideal points. They're the main "target" of the package, I believe. I'm just upvoting that haha :)

**Comment by RobertMyles** [comment]
Let's leave this for a future version.
