### ISSUE TITLE
End game?

### ISSUE THREAD

**Issue by briatte** [RobertMyles/congressbr#24]
Dear repo authors – @danilofreire @duarteguilherme and @RobertMyles,

May I ask what's the 'end game' for this repo?

Context: I've written a [bunch of similar scrapers](https://github.com/briatte/parlnet) for Europe, and am thinking about writing similar scrapers for Latin America if it makes sense. My research topic is [legislative collaboration, and bill co-sponsorships especially](http://f.briatte.org/research/#legislative-networks).

**Comment by RobertMyles** [comment]
Hi briatte. We're interested in legislative analysis, principally roll-call votes, and the repo is linked with that type of work. We're open to collaborations and suggestions, though, so if you have some ideas for working with the data from the package, we'd love to hear about them.

**Comment by duarteguilherme** [comment]
I'm really interested in participating in this type of project. For such endeavor, I think we should have an initial model or project in order to integrate all the scrapers. 
We had a hard time trying to integrate  Brazilian Chamber of Deputies and Senate data. I believe, thus, a project for integrating other countries must be well designed and simple.

**Comment by briatte** [comment]
Thanks for the quick answers!

I'm planning to add vote scrapers to my repo this summer, although I'm more interested in non-roll-call forms of legislative information.

> For such endeavor, I think we should have an initial model in order to integrate all the scrapers.

This is really hard. I've looked at 20+ countries, including several bicameral ones, and the model, if it exists, is elusive. I don't say much about this in my [research note](http://f.briatte.org/research/parlnet-note.pdf), but the [appendix](http://f.briatte.org/research/parlnet-appendix.pdf) says a bit more.

I'll come back to you both when I get the time I need to start editing the scrapers again.

**Comment by RobertMyles** [comment]
Sure, then we can chat more about it and see what's possible.
