### ISSUE TITLE
Checking differences between Windows and Linux

### ISSUE THREAD

**Issue by duarteguilherme** [RobertMyles/congressbr#27]
We must check if the package is working on Windows and on Linux.

**Comment by RobertMyles** [comment]
You have Linux, right? We could check it with that. 
For Windows, I can check it on another computer or we can use [here](https://win-builder.r-project.org/).

**Comment by duarteguilherme** [comment]
On linux , it's working.

**Comment by RobertMyles** [comment]
And the non-ascii?

**Comment by duarteguilherme** [comment]
that's not a big deal, because the encoding on Linux is utf-8 as well.

**Comment by danilofreire** [comment]
It seems to work fine on Ubuntu 16.04.2 LTS. No issues so far.

**Comment by danilofreire** [comment]
We close the issue after the run the final beta on Windows. I have a Windows 8.1 partition on my PC if necessary. Or we can use [winbuilder](https://win-builder.r-project.org/) as Rob suggested.

**Comment by RobertMyles** [comment]
I'm closing this because we can use devtools to check it.
