### ISSUE TITLE
To do: vignette for Senate, vignette for Chamber

### ISSUE THREAD

**Issue by danilofreire** [RobertMyles/congressbr#3]
So far we've got no vignettes for the Senate and the Chamber. It would be nice to write at least one vignette describing the data, presenting summary statistics and showing what the basic functions can do.

**Comment by danilofreire** [comment]
Guys, what do you think about writing an article for [the R Journal](https://journal.r-project.org/)? It would serve as a good introduction to the package (with vignettes, etc) and it's peer-reviewed. Here's [an example article](https://journal.r-project.org/archive/2014-1/leeper.pdf).  What do you guys think?

**Comment by RobertMyles** [comment]
Great idea, man, I'm on board.

**Comment by danilofreire** [comment]
Great, we work on that after/if the package is accepted on CRAN.

**Comment by danilofreire** [comment]
[LaTeX](https://www.overleaf.com/latex/templates/r-journal-template/hpqfkmnyghpp#.WMRLmXWLTQo) and [RMarkdown](https://github.com/rstudio/rticles) templates for the R Journal (just for later reference)

**Comment by danilofreire** [comment]
Close with [this commit](https://github.com/RobertMyles/congressbr/commit/e1888a56a888327b1b4c0f9b78e3f0a7553ff1c7)
