### ISSUE TITLE
cham_bills e sen_bills_current

### ISSUE THREAD

**Issue by maxstabile** [RobertMyles/congressbr#33]
Oi, pessoal, parabéns pelo trabalho.

Não entendi muito bem uma coisa:
cham_bills(type = "PL", year = 2017)
retorna a lista de PLs de 2017
a sua função homóloga no senado não deveria ser sen_bills? Eu usei aqui
sen_bills_current(type = "PLS", year = 2017)

É isso mesmo, certo?

E no lugar de sen_bils não seria mais fácil ser sen_bils_info igual a cham_bill_info?

Abs!

**Comment by RobertMyles** [comment]
Tá certo, um dos issues é sobre isso (#26)

**Comment by duarteguilherme** [comment]
Bom ponto, @RobertMyles , vamos deixar este issue aberto para padronizar cham_bills e sen_bills.
