### ISSUE TITLE
Problema em um for no "sen_bills"

### ISSUE THREAD

**Issue by maxstabile** [RobertMyles/congressbr#34]
Oi,

estou tentando rodar

PLsSenado <- sen_bills_current(type = "PLS", year = 2017)
datalist = list()
for(i in 1:nrow(PLsSenado)){
  cat(i, "\n ")
  dat2 <- congressbr::sen_bills(PLsSenado$bill_id[i])
  datalist[[i]] <- dat2 
}

E apareceu esse erro aqui

 Error: Each variable must be a 1d atomic vector or list.
Problem variables: 'bill_indexing'

Estou fazendo alguma coisa errada?

Abs

**Comment by RobertMyles** [comment]
O problema é esse bill aqui (outros também): 

```
sen_bills("128289")
```

Por enquanto, pode usar 

```
for(i in 1:nrow(PLsSenado)){
  cat(i, "\n ")
  dat2 <- try(sen_bills(PLsSenado$bill_id[i]), silent = F)
  if(class(dat2) == 'error'){
    next
  }
  datalist[[i]] <- dat2
  Sys.sleep(2)
}
```

E eu vou adicionar mensagens de erro mais informativos.
