### ISSUE TITLE
awesome-brazil-data

### ISSUE THREAD

**Issue by juliohm** [RobertMyles/congressbr#38]
Hi Robert,

I have included your project in a list: https://github.com/juliohm/awesome-brazil-data

Thanks for the effort, please feel free to close this issue at any time. Just wanted to share the initiative with you and your collaborators.

Best,

**Comment by RobertMyles** [comment]
Hi Júlio,

Cool, nice initiative! You might also find some other data-access packages (mainly for R) on my GitHub page and that of Julio (@jtrecenti). Maybe @danilofreire and @duarteguilherme might know of some other datasets too.

**Comment by juliohm** [comment]
Thanks Robert, I will definitely check it. Please feel free to submit a PR there.

Best,
