### ISSUE TITLE
add Senate "serviços"

### ISSUE THREAD

**Issue by danilofreire** [RobertMyles/congressbr#4]
Every "serviço" on this Senate page has to be done: [http://legis.senado.gov.br/dadosabertos/docs/resources.html](http://legis.senado.gov.br/dadosabertos/docs/resources.html).

**Comment by RobertMyles** [comment]
- [x] AgendaService 
- [] AutorService
- [] BlocoParlamentarService
- [] DetalheComissaoService
- [] DistribuicaoMateriaService
- [] GlossarioService
- [] LegislacaoService
- [] ListaBlocoParlamentarService
- [] ListaComissaoService
- [] ListaMateriaComissaoService
- [] ListaMateriaPrazoService
- [] ListaSenadorService 
- [] MateriaService
- [] OrcamentoService
- [] ParlamentarService
- [] PesquisaMateriaService
- [] PlenarioService
- [] ReuniaoService

**Comment by RobertMyles** [comment]
MateriaService:  

- [x] legislaturaatual
- [x] assuntos
- [x] {sigla}{numero}{ano}
- [x] {codigo}
- [x] completa  -- unnecessary
- [x] subtipos
- [x] tiposPrazo
- [x] tiposNorma
- [] tipoNatureza
- [] situacoes
- [] atualizadas
- [x] situacaoatual
- [x] tramitando
- [] movimentacoes
- [] relatorias
- [] emendas
- [] votacoes
- [] textos
- [] ordia
- [] atualizacoes
- [] tipoatualizacoes
- [] locais

**Comment by RobertMyles** [comment]
Plenário Service:
-[x] resultado `sen_plenary_result()`
