### ISSUE TITLE
Translation table

### ISSUE THREAD

**Issue by RobertMyles** [RobertMyles/congressbr#5]
It (might) be nice to have a simple data frame with English translations of common terms found in the API results.  Something straightforward, like 2 columns: 

``` 

Term                                     Translation 

SiglaCasaComissao             Abbreviation of Legislative House

```

this type of thing.

**Comment by danilofreire** [comment]
That would be great. It shouldn't take very long to translate the terms. I can do that, and if someone else wants to help me out, that would be nice, too. It's probably not a top priority now, but I agree it's a nice feature. It would help non-Portuguese speakers to use the package.

**Comment by RobertMyles** [comment]
For a later version.
