### ISSUE TITLE
Create a wiki

### ISSUE THREAD

**Issue by RobertMyles** [RobertMyles/congressbr#8]

**Comment by danilofreire** [comment]
What type of wiki do you have in mind?

**Comment by RobertMyles** [comment]
You know what? On second thoughts, I think some good vignettes and a detailed README would be much better.

**Comment by danilofreire** [comment]
Me too. It's probably what people will read first.

**Comment by duarteguilherme** [comment]
We can write the wiki directly on README file

**Comment by RobertMyles** [comment]
Yeah, that's better.

**Comment by danilofreire** [comment]
Sure, that would be nice.
